# ------------------------------------------------------------------------- #
# spring.application.name can be enabled when running locally. If deploying to Azure Spring Cloud, leave this commented out #
# ------------------------------------------------------------------------- #

# spring:
#   application:
#     name: greeting

