server:
    port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Ajsalemo/SpringCloudLocal
          skipSslValidation: true
          # Checkout the 'main' branch
          default-label: main
